adding fix to support concrete size arrays, with large indicies

diff --git a/jpf-symbc/bin/jr-sv-comp b/jpf-symbc/bin/jr-sv-comp
--- a/jpf-symbc/bin/jr-sv-comp
+++ b/jpf-symbc/bin/jr-sv-comp
@@ -2,6 +2,7 @@
 SECONDS=0
 DURATION=800
 DEPTH_LIMIT[0]=13
+DEPTH_LIMIT[1]=17
 DEPTH_LIMIT[1]=21
 DEPTH_LIMIT[2]=156
 
@@ -43,8 +44,17 @@ echo "Empty benchmark or property file"
 exit 1
 fi
 
-# we ignore the property file (there is only one property at the moment)
-# we ignore the witness file (not used yet)
+  ASSERTION_MODE="FALSE"
+  RUNTIME_EXCEPTION_MODE="FALSE"
+  grep "assert" $PROP_FILE
+  if [ $? -eq 0 ]; then
+    ASSERTION_MODE="TRUE"
+  fi
+
+  grep "exception" $PROP_FILE
+  if [ $? -eq 0 ]; then
+    RUNTIME_EXCEPTION_MODE="TRUE"
+  fi
 
 LOG=`mktemp -t jpf-log.XXXXXX`
 DIR=`mktemp -d -t jpf-benchmark.XXXXXX`
@@ -94,6 +104,9 @@ do
   echo "singlePathOptimization=true" >> $DIR/config.jpf
   #echo "symbolic.optimizechoices=false" >> $DIR/config.jpf
   echo "symbolic.fp = true" >> $DIR/config.jpf
+  if [ $RUNTIME_EXCEPTION_MODE = "TRUE" ] ; then
+    echo "search.multiple_errors = true" >> $DIR/config.jpf
+  fi
 
 
   # run Java Ranger
@@ -123,13 +136,27 @@ do
       RESULT="SAFE"
     fi
   else
-    grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
-    if [ $? -eq 0 ]; then
-      echo " state3 = UNSAFE"
-      RESULT="UNSAFE"
+    if [ $ASSERTION_MODE = "TRUE" ]; then
+      grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
+      if [ $? -eq 0 ]; then
+        echo " state3 = UNSAFE"
+        RESULT="UNSAFE"
+      else
+        echo " state4 = UNKNOWN"
+        RESULT="UNKNOWN"
+      fi
+    elif [ $RUNTIME_EXCEPTION_MODE = "TRUE" ]; then
+      grep "java.lang.*Exception" $LOG > /dev/null
+      if [ $? -eq 0 ]; then
+        echo " state3 = UNSAFE"
+        RESULT="UNSAFE"
+      else
+        echo " state4 = UNKNOWN"
+        RESULT="UNKNOWN"
+      fi
     else
-      echo " state4 = UNKNOWN"
-      RESULT="UNKNOWN"
+      echo unsupported case. Failing
+      exit 1;
     fi
   fi
 
